import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarTop from "@/components/NavbarTop/NavbarTop";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<div className="min-h-screen flex flex-col">
      
      <div className="hidden md:block w-full">
        <NavbarTop />
      </div>

      <div className="flex-grow w-full mt-12"> 
      {children}
      </div>
    </div>


       
      </body>
    </html>
  );
}
